export enum SettoreTypes {
  TRIB_LAT_OVEST_TERRACINA = "Trib. Lat. Ovest Terracina",
  TRIB_CENTRALE_TERRACINA = "Trib. Centrale Terracina",
  TRIB_LAT_EST_TERRACINA = "Trib. Lat. Est Terracina",
  CURVA_EST = "Curva Est",
  TRIB_LAT_EST_ARGENTO = "Trib. Lat. Est Argento",
  TRIB_CENTRALE_ARGENTO = "Trib. Centrale Argento",
  TRIB_LAT_OVEST_ARGENTO = "Trib. Lat. Ovest Argento",
  SETTORE_OSPITI = "Settore Ospiti",
  CURVA_OVEST = "Curva Ovest",
}

export enum TicketType {
  TRIB_LAT_OVEST_TERRACINA_OVER = "Trib. Lat. Ovest Terracina - Intero Over 24",
  TRIB_LAT_OVEST_TERRACINA_RIDOTTO = "Trib. Lat. Ovest Terracina - Ridotto 3-24 anni",
  TRIB_CENTRALE_TERRACINA_OVER = "Trib. Centrale Terracina - Intero Over 24",
  TRIB_CENTRALE_TERRACINA_RIDOTTO = "Trib. Centrale Terracina - Ridotto 3-24 anni",
  TRIB_LAT_EST_TERRACINA_OVER = "Trib. Lat. Est Terracina - Intero Over 24",
  TRIB_LAT_EST_TERRACINA_RIDOTTO = "Trib. Lat. Est Terracina - Ridotto 3-24 anni",
  CURVA_EST_OVER = "Curva Est - Intero Over 24",
  CURVA_EST_RIDOTTO = "Curva Est - Ridotto 3-24 anni",
  TRIB_LAT_EST_ARGENTO_OVER = "Trib. Lat. Est Argento - Intero Over 24",
  TRIB_LAT_EST_ARGENTO_RIDOTTO = "Trib. Lat. Est Argento - Ridotto 3-24 anni",
  TRIB_CENTRALE_ARGENTO_OVER = "Trib. Centrale Argento - Intero Over 24",
  TRIB_CENTRALE_ARGENTO_RIDOTTO = "Trib. Centrale Argento - Ridotto 3-24 anni",
  TRIB_LAT_OVEST_ARGENTO_OVER = "Trib. Lat. Ovest Argento - Intero Over 24",
  TRIB_LAT_OVEST_ARGENTO_RIDOTTO = "Trib. Lat. Ovest Argento - Ridotto 3-24 anni",
  SETTORE_OSPITI_OVER = "Settore Ospiti - Intero Over 24",
  SETTORE_OSPITI_RIDOTTO = "Settore Ospiti - Ridotto 3-24 anni",
  CURVA_OVEST_OVER = "Curva Ovest - Intero Over 24",
  CURVA_OVEST_RIDOTTO = "Curva Ovest - Ridotto 3-24 anni",
}
